# Generated by Django 2.2 on 2019-10-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealthinfo',
            name='lbs_per_week_goal',
            field=models.IntegerField(default=0, verbose_name='Pounds Per Week'),
        ),
    ]
