# Generated by Django 2.2 on 2019-10-23 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalList',
            fields=[
                ('list_name', models.CharField(max_length=100, verbose_name='Listname')),
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_json', models.TextField(verbose_name='Rank List')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterList',
            fields=[
                ('list_name', models.CharField(max_length=100, verbose_name='Listname')),
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=35, verbose_name='Item Name')),
                ('votes', models.IntegerField(default=0)),
                ('master_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemranker.MasterList')),
            ],
        ),
    ]
